// Assembles README.md from config + the generated hero/tool-wall.
// Lean by intent: the hero, a two-line identity, links, and one small accent
// of capability (the tool wall). No feed, no stats grid — the essence, not a
// barrage. The feed/stats modules still exist in the machine; they're just not
// surfaced here.
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadJSON, ROOT } from "./lib/svg.mjs";

const p = loadJSON("config/profile.json");
const pages = p.pagesUrl;

// Cache-bust so GitHub's image proxy re-fetches updated assets each run.
const stamp = process.env.BUILD_STAMP || "dev";
const img = (path, alt) => `generated/${path}?v=${stamp}" alt="${alt}`;

const taglineLines = p.tagline.map((l) => `<samp>${l}</samp>`).join("<br>");

const md = `<!-- ============================================================
     This file is GENERATED by scripts/assemble-readme.mjs.
     Do not edit by hand — edit config/*.json and let the
     "profile-update" workflow regenerate it.
     ============================================================ -->

<p align="center">
  <a href="${pages}">
    <img src="${img("hero.gif", "Julius Bautista")}" width="100%" />
  </a>
</p>

<h1 align="center">${p.fullName}</h1>
<p align="center">
${taglineLines}
</p>

<p align="center">
  <a href="${pages}"><strong>Portfolio</strong></a>
  &nbsp;·&nbsp;
  <a href="${p.links.linkedin}">LinkedIn</a>
  &nbsp;·&nbsp;
  <a href="${p.links.website}">juliusbautista.com</a>
  &nbsp;·&nbsp;
  <a href="${p.links.email}">Email</a>
</p>

<br>

<p align="center">
  <img src="${img("tool-wall.svg", "Toolkit")}" width="82%" />
</p>
`;

writeFileSync(join(ROOT, "README.md"), md);
console.log("assembled README.md (lean)");
