// Assembles README.md from config + the generated art.
// Layout: hero → identity + links → daily quote → toolkit → signal feed.
// Each block's SVG carries its own heading, so the markdown stays clean.
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { join } from "node:path";
import { loadJSON, ROOT } from "./lib/svg.mjs";

const p = loadJSON("config/profile.json");
const pages = p.pagesUrl;

// Cache-bust by CONTENT HASH: the ?v= only changes when the asset changes, so
// the README (and camo's cache) update on real changes — no daily churn from
// the static hero, but the feed/quote refresh when they move.
const ver = (path) => {
  const abs = join(ROOT, "generated", path);
  if (!existsSync(abs)) return "0";
  return createHash("sha1").update(readFileSync(abs)).digest("hex").slice(0, 8);
};
const img = (path, alt) => `generated/${path}?v=${ver(path)}" alt="${alt}`;

const taglineLines = p.tagline.map((l) => `<samp>${l}</samp>`).join("<br>");

const md = `<!-- ============================================================
     This file is GENERATED by scripts/assemble-readme.mjs.
     Do not edit by hand — edit config/*.json and let the
     "profile-update" workflow regenerate it.
     ============================================================ -->

<p align="center">
  <a href="${pages}">
    <img src="${img("hero.gif", "Julius Bautista")}" width="100%" />
  </a>
</p>

<h1 align="center">${p.fullName}</h1>
<p align="center">
${taglineLines}
</p>

<p align="center">
  <a href="${pages}"><strong>Portfolio</strong></a>
  &nbsp;·&nbsp;
  <a href="${p.links.linkedin}">LinkedIn</a>
  &nbsp;·&nbsp;
  <a href="${p.links.website}">juliusbautista.com</a>
  &nbsp;·&nbsp;
  <a href="${p.links.email}">Email</a>
</p>

<br>

<p align="center">
  <img src="${img("quote.svg", "Quote of the day")}" width="82%" />
</p>

<br>

<p align="center">
  <img src="${img("tool-wall.svg", "Toolkit")}" width="88%" />
</p>

<br>

<p align="center">
  <img src="${img("feed.svg", "Signal — the latest from around the industry")}" width="88%" />
</p>

<p align="center"><sub>◷ Quote rotates daily · feed pulled from the field · auto-updated by GitHub Actions</sub></p>
`;

writeFileSync(join(ROOT, "README.md"), md);
console.log("assembled README.md");
