// Assembles README.md from config + the generated art.
// Layout: hero → identity + links → daily quote → toolkit → signal feed.
// Each block's SVG carries its own heading, so the markdown stays clean.
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { join } from "node:path";
import { loadJSON, loadCSV, truthy, ROOT } from "./lib/svg.mjs";

// "Signal source pools" — the enabled sources grouped by track, from feeds.csv.
function sourcePools() {
  const rows = loadCSV("config/feeds.csv").filter((r) => truthy(r.enabled));
  const order = [];
  const by = {};
  for (const r of rows) {
    if (!by[r.category]) { by[r.category] = []; order.push(r.category); }
    by[r.category].push(r.source);
  }
  const lines = order.map((c) => `<strong>${c}</strong> — ${by[c].join(" · ")}`);
  return `<details>\n<summary>Feed sources</summary>\n<br>\n${lines.join("<br>\n")}\n</details>`;
}

const p = loadJSON("config/profile.json");
const pages = p.pagesUrl;

// Cache-bust by CONTENT HASH: the ?v= only changes when the asset changes, so
// the README (and camo's cache) update on real changes — no daily churn from
// the static hero, but the feed/quote refresh when they move.
const ver = (path) => {
  const abs = join(ROOT, "generated", path);
  if (!existsSync(abs)) return "0";
  return createHash("sha1").update(readFileSync(abs)).digest("hex").slice(0, 8);
};
const img = (path, alt) => `generated/${path}?v=${ver(path)}" alt="${alt}`;

// Feed: header + one CLICKABLE SVG per article + footer, stacked with ZERO gap
// via HTML-comment newline-eaters so they read as a single card. Each item row
// links to its article; the header/footer don't.
const feed = loadJSON("config/feed.json");
const feedParts = [
  `<img src="${img("feed-header.svg", "Feed")}" width="720" />`,
  ...feed.items.map((it, i) => `<a href="${it.link}"><img src="${img(`feed-item-${i}.svg`, `${it.track} — ${it.source}`)}" width="720" /></a>`),
  `<img src="${img("feed-footer.svg", "Feed")}" width="720" />`,
];
const feedStack = `<div align="center">${feedParts.join("<!--\n-->")}</div>`;


const md = `<!-- ============================================================
     This file is GENERATED by scripts/assemble-readme.mjs.
     Do not edit by hand — edit config/*.json and let the
     "profile-update" workflow regenerate it.
     ============================================================ -->

<p align="center">
  <a href="${pages}">
    <img src="${img("hero.gif", "Julius Bautista")}" width="100%" />
  </a>
</p>

<h1 align="center">${p.fullName}</h1>
<p align="center"><sub>${p.subtitle}</sub></p>

<p align="center">
  <a href="${pages}"><strong>Portfolio</strong></a>
  &nbsp;·&nbsp;
  <a href="${p.links.linkedin}">LinkedIn</a>
  &nbsp;·&nbsp;
  <a href="${p.links.website}">juliusbautista.com</a>
  &nbsp;·&nbsp;
  <a href="${p.links.email}">Email</a>
</p>

<br>

<p align="center">
  <img src="${img("quote.svg", "Quote of the day")}" width="82%" />
</p>

<br>

<p align="center">
  <img src="${img("tool-wall.svg", "Toolkit")}" width="88%" />
</p>

<br>

${feedStack}

<p align="center"><sub>◷ Quote rotates daily · feed refreshes twice daily · auto-updated by GitHub Actions</sub></p>

${sourcePools()}
`;

writeFileSync(join(ROOT, "README.md"), md);
console.log("assembled README.md");
